### ISSUE TITLE
Cannot access blob storage in azure-virtual-machine-cost-estimator.pbix

### ISSUE THREAD

**Issue by hectorcubillos** [microsoft/CloudAdoptionFramework#191] opened 2023-11-21 18:29 UTC
I'm opening this issue since it's not working again.
>
https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/889

**Comment by Zimmergren** [comment] 2023-12-13 15:40
Duplicate of #190 
#please-close

**Closed** 2023-12-13 15:41 UTC
